### ISSUE TITLE
hmset object should only set own enumerable properties

### ISSUE THREAD

**Issue by zaim** [rootslab/syllabus#1]
Hello!

This could be an issue with Sermone, but since I'm explicitly using Syllabus, I'm posting this here.

Basically, `hmset(key, object)` should support "custom" objects, that is, only use the object's own enumerable properties, not its prototypes.

``` javascript
function CustomObject () {
  this.id = 1
  this.name = 'value'
}

CustomObject.prototype.PROTO_METHOD = function () {}
CustomObject.prototype.PROTO_PROPERTY = 'prop'

const obj = new CustomObject()
const syll = Syllabus(true)
const cmd = syll.commands.hmset('key', obj)

console.log(cmd.ecmd)
```

Output:

```
*10
$5
HMSET
$3
key
$2
id
$1
1
$4
name
$5
value
$12
PROTO_METHOD
$14
function () {}
$14
PROTO_PROPERTY
$4
prop
```

I believe PROTO_METHOD and PROTO_PROPERTY shouldn't be added to the hash.

My use case here is that I'm using domain-driven design and have custom "Model" classes of the objects I'd like to store in redis. These models classes might have methods attached to its prototype such as validators, etc.

A workaround for now is to simply do a deep clone, but it'd be more convenient to simply pass the object directly to hmset.

**Comment by rootslab** [comment]
Hi @zaim, this behaviour is due to the use of the __Bolgia.toArray__ method in __Syllabus.hmset__, before encoding the command with __Sermone.encode__ https://github.com/rootslab/syllabus/blob/d18359c3866d423ee35d5551dd22623a215c6dc6/lib/commands/hashes.js#L78
I have added a new method to __[Bolgia](https://github.com/rootslab/bolgia)__ (toArrayEnum), then,  in a future __Syllabus__ release, you could specify if you want to list only enumerable properties, when using __Syllabus.hmset__

Thanks.
